import { useState } from "react";
import reactLogo from "./assets/react.svg";

import "./App.css";
import Header from "./components/Header";
import { Body } from "./components/Body";
import { HeadProvider } from "react-head";

function App() {
  return (
    <div className="">
      <HeadProvider>
        <title>Rent Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="reactLogo" />
      </HeadProvider>
      <Header />
      <Body />
    </div>
  );
}

export default App;
